name: Build and deploy Node.js app to Azure Web App - tech0-gen-7-step4-studentwebapp-pos-41

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: my-app  # 相対パスで指定

      - name: List files before build
        run: ls -R my-app  # 圧縮前のファイルを表示

      - name: Build and test
        run: |
          npm run build --if-present
          npm run test --if-present
        working-directory: my-app  # 相対パスで指定

      - name: List files before zipping
        run: ls -R my-app  # 圧縮するファイルを確認

      - name: Zip artifact for deployment
        run: |
          echo "Creating release.zip..."
          zip -r release.zip .  # 現在のディレクトリ内のすべてを圧縮
          echo "release.zip created."
        working-directory: my-app  # 相対パスで指定

      - name: List files after zipping
        run: ls -R my-app  # 圧縮後のファイルを表示

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app  # アーティファクト名
          path: ./my-app/release.zip  # アップロードするファイルのパス

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app  # 同じアーティファクト名

      - name: Unzip artifact for deployment
        run: unzip release.zip  # アーティファクトを解凍
        working-directory: my-app  # 相対パスで指定

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen-7-step4-studentwebapp-pos-41'
          slot-name: 'Production'
          package: my-app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFIL }}
